In [9]:
import numpy as np

In [10]:
vec = np.array([1, 2, 3])
vec

array([1, 2, 3])

In [11]:
col = np.array([[1], [2], [3]])
col

array([[1],
       [2],
       [3]])

In [13]:
mat = np.array(
    [
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
    ]
)
mat

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [14]:
from scipy import sparse

In [15]:
mat = np.array([[0, 0], [0, 1], [3, 0]])
ms = sparse.csr_matrix(mat)
ms

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>

In [20]:
print(ms)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [18]:
ml = np.array([[0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [3, 0, 0, 0, 0, 0]])
mls = sparse.csr_matrix(ml)
mls

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 6)>

In [19]:
print(mls)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 6)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [21]:
vec = np.array([1, 2, 3, 4, 5, 6])
mat = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [
            7,
            8,
            9,
        ],
    ]
)
print(vec)
print(mat)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
vec[2]

np.int64(3)

In [23]:
mat[1, 1]

np.int64(5)

In [24]:
vec[:]

array([1, 2, 3, 4, 5, 6])

In [25]:
vec[:3]

array([1, 2, 3])

In [26]:
vec[3:]

array([4, 5, 6])

In [27]:
mat[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
mat[:, 1:2]

array([[2],
       [5],
       [8]])

In [29]:
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
mat.shape

(3, 4)

In [30]:
mat.size

12

In [31]:
mat.ndim

2

In [33]:
mat = np.arange(1, 10).reshape(3, 3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
add100 = lambda i: i + 100

vfun = np.vectorize(add100)
vfun

In [35]:
vfun(mat)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [36]:
mat + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [37]:
np.max(mat)

np.int64(9)

In [38]:
np.min(mat)

np.int64(1)

In [39]:
np.max(mat, 0)

array([7, 8, 9])

In [40]:
np.max(mat, 1)

array([3, 6, 9])

In [41]:
np.mean(mat)

np.float64(5.0)

In [42]:
np.var(mat)

np.float64(6.666666666666667)

In [43]:
np.std(mat)

np.float64(2.581988897471611)

In [44]:
np.mean(mat, 0)

array([4., 5., 6.])

In [45]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
mat.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [47]:
mat.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [48]:
mat.size

12

In [49]:
mat.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
mat.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [63]:
np.arange(1, 7).reshape(1, -1).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [66]:
mat.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
mat.reshape(1, -1).shape

(1, 9)

In [69]:
np.linalg.matrix_rank(mat)

np.int64(2)

In [70]:
np.linalg.det(mat)

np.float64(-9.51619735392994e-16)

In [71]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
mat.diagonal()

array([1, 5, 9])

In [73]:
mat.diagonal(offset=1)

array([2, 6])

In [74]:
mat.diagonal(offset=-1)

array([4, 8])

In [75]:
mat.trace()

np.int64(15)